# Configuration file version
apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: db:5432
    user: my-username
    secureJsonData:
      password: my-password
    jsonData:
      database: mydb
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1507 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
