# Configuration file version
apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: db:3306
    user: my-username
    secureJsonData:
      password: my-password
    jsonData:
      database: mydb
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
