version: "3.8"
services:
  server-app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server-app
    ports:
      - '3000:3000'
  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - '3010:3000'
    volumes:
      - ./packages/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./packages/grafana/provisioning:/etc/grafana/provisioning
      - ./packages/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${AUTH_GENERIC_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_USER_POOL_DOMAIN=${AUTH_GENERIC_OAUTH_USER_POOL_DOMAIN}/oauth2/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${AUTH_GENERIC_OAUTH_USER_POOL_DOMAIN}/oauth2/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=${AUTH_GENERIC_OAUTH_USER_POOL_DOMAIN}/oauth2/userInfo

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    name: mysql-data
