services:

  browser-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: browser-app-dev
    ports:
      - 5173:5173
    env_file:
      - ./packages/browser-app/.env.local
    volumes:
      - ./packages/browser-app:/usr/src/app/packages/browser-app
      - /usr/src/app/packages/browser-app/node_modules

  server-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-app-dev
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://my-username:my-password@db:5432/mydb?sslmode=disable
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - ./packages/server-app:/usr/src/app/packages/server-app
      - /usr/src/app/packages/server-app/node_modules
    depends_on:
      db:
        condition: service_healthy

  plc-fake:
    build:
      context: .
      dockerfile: Dockerfile
      target: plc-fake
    environment:
      DATABASE_URL: postgres://my-username:my-password@db:5432/mydb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - '3010:3010'
    volumes:
      - ./packages/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./packages/grafana/provisioning:/etc/grafana/provisioning
      - grafana-config-data:/var/lib/grafana
    environment:
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${AUTH_GENERIC_OAUTH_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: ${AUTH_GENERIC_OAUTH_USER_POOL_DOMAIN}/oauth2/authorize
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ${AUTH_GENERIC_OAUTH_USER_POOL_DOMAIN}/oauth2/token
      GF_AUTH_GENERIC_OAUTH_API_URL: ${AUTH_GENERIC_OAUTH_USER_POOL_DOMAIN}/oauth2/userInfo
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.7-alpine3.20
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: my-username
      POSTGRES_PASSWORD: my-password
    ports: 
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "my-username", "-d", "mydb"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  postgres-data:
  grafana-config-data:
