version: "3.8"
services:
  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - '3000:3000'
    volumes:
      - ./grafana.ini/:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${AUTH_GENERIC_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=${AUTH_GENERIC_OAUTH_AUTH_URL}
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${AUTH_GENERIC_OAUTH_TOKEN_URL}
      - GF_AUTH_GENERIC_OAUTH_API_URL=${AUTH_GENERIC_OAUTH_API_URL}
